### ISSUE TITLE
Regex generico

### ISSUE THREAD

**Issue by Vestima** [Vikaparra/CSV-to-JSON-NodeJs#3]
[Esse regex](https://github.com/Vikaparra/CSV-to-JSON-NodeJs/blob/main/index.js#L64) tá pegando basicamente qualquer palavra, acho que não seria muito útil.

Se tiver "kkkkkk" no grupo, o regex vai pegar.

Para aceitar Sala e Turma ce pode fazer:

`(Sala \d*)|(Turma \d*)`

**Comment by Vikaparra** [comment]
Corrigido de acordo com o que discutimos
