### ISSUE TITLE
Usar o evento 'data' do CreateReadStream

### ISSUE THREAD

**Issue by Vestima** [Vikaparra/CSV-to-JSON-NodeJs#4]
Ao inves de fazer [esse forEach](https://github.com/Vikaparra/CSV-to-JSON-NodeJs/blob/main/index.js#L19) no evento end, você pode chamar a função `fillStudents` na variavel `data` no evento `data`.

`.on('data', (data) => {`
     `results.push(data);`
     `fillStudents(data);`
`})`

**Comment by Vikaparra** [comment]
Corrigido (ai não precisou nem do results.push(data))
