### ISSUE TITLE
(TOC) Padronizar as tipagens de variável

### ISSUE THREAD

**Issue by Vestima** [Vikaparra/CSV-to-JSON-NodeJs#6]
As declarações de variaveis tao diferentes ao longo do codigo, eu achei isso meio confuso.

Deve ter algum padrão/boas praticas de javascript pra esse problema de tipagem, acho que vale investigar

Em alguns lugares:

- [Usa var](https://github.com/Vikaparra/CSV-to-JSON-NodeJs/blob/main/index.js#L66)
- [Usa let](https://github.com/Vikaparra/CSV-to-JSON-NodeJs/blob/main/index.js#L50)
- [Usa const](https://github.com/Vikaparra/CSV-to-JSON-NodeJs/blob/main/index.js#L96)
- [Não usa nada ](https://github.com/Vikaparra/CSV-to-JSON-NodeJs/blob/main/index.js#L45)

**Comment by Vikaparra** [comment]
Pesquisando as boas práticas o que fiz foi substituir tudo o que não seria sobrescrito por "const", e aquilo que precisaria ser sobrescrito por "let"
